name: regex_builder
description: A declarative way to write regular expressions in Dart.
version: 0.1.0+7
homepage: https://github.com/ailtonvivaz/regex_builder

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
