name: regex_builder
description: A Dart library that allows you to write regular expression in a declarative way.
version: 0.1.0+8
homepage: https://github.com/ailtonvivaz/regex_builder

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
